### PR TITLE
LegacyEthernetTest: Check Ethernet.hostByName() for failure

### PR DESCRIPTION
**Pull request by ssilverman**
Spec here: https://www.arduino.cc/reference/en/libraries/wifinina/wifi.hostbyname/

### CODE REVIEW

**Comment by ssilverman** [comment]
Fixes #1

**Comment by ssilverman** [comment]
Sorry for the force-push noise. I erred in pushing some future commits to this branch.

**Comment by ssilverman** [comment]
Did I mess something up, or did you not want this PR?

**Comment by ssilverman** [comment]
Oh, I see, you force-pushed on top of the "init" commit for some reason? (I don't understand why, but so be it.) I'll redo this PR...

**Comment by JAndrassy** [comment]
sorry

**Pull request closed without merging**
